name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run:
        npm ci
    - name: Build
      run:
        npm run build:client:prod
        npm run build:server:prod
    - name: Test
      run:
        npm test
        npm run test:codecov
        npm run test:browserstack
        npm run test:cypress:run
      env:
        CI: true
        BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
        BROWSERSTACK_TOKEN: ${{ secrets.BROWSERSTACK_TOKEN }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 
        CYPRESS_TOKEN: ${{ secrets.CYPRESS_TOKEN }} 
